version: "3"

containers:
- name: workstation
  image: gcr.io/instruqt/ubuntu-2204
  shell: /bin/bash
  memory: 4096

# Uncomment for VM-based tracks:
# virtualmachines:
# - name: server
#   image: my-gcp-project/my-custom-image
#   shell: /bin/bash
#   machine_type: n1-standard-4

# Uncomment for cloud accounts:
# gcp_projects:
# - name: my-gcp
#   services:
#   - container.googleapis.com
#   roles:
#   - roles/container.admin

# aws_accounts:
# - name: my-aws
#   managed_policies:
#   - arn:aws:iam::aws:policy/AdministratorAccess

# Uncomment to use team secrets:
# secrets:
# - name: MY_SECRET_KEY
